<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="../base.css" />
    <title>async-await</title>
  </head>
  <body>
    <script>
      function wait(ms = 0) {
        return new Promise(resolve => {
          setTimeout(resolve, ms);
        });
      }

      async function makePizza(toppings = []) {
        // const pizzaPromise
        let bakeTime = 500 + toppings.length * 200;

        console.log("we have recieved your order");
        await wait(1000);
        return new Promise(async function(resolve, reject) {
          console.log("checking for pinapple one sec...");
          setTimeout(function() {
            toppings.includes("pinapple")
              ? reject("we dont serve your kind... savage")
              : console.log(
                  `pizza is cooking wait time is ${bakeTime / 1000} seconds`,
                  setTimeout(function() {
                    resolve(`mmmhhh pizza pizza oh and with ${toppings}`);
                  }, bakeTime)
                );
          }, 2000);
        });
        //return pizzaPromise;
      }

      //way 1 to handle errors with async await
      async function goHead() {
        try {
          const pizza = await makePizza(["piapple"]);
          console.log(pizza);
        } catch (err) {
          console.log(err);
        }
      }
      goHead();

      function handleError(err) {
        console.log("not again!!");
      }
      async function method2() {
        //handles the error at the time you define the function
        const pizza = await makePizza(["pinapple"]);
        console.log(pizza);
        return pizza;
      }
      method2().catch(handleError);
    </script>
  </body>
</html>
